// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#include <cstdbool>
#include <cstdint>

#include "flatbuffers/flatbuffers.h"
#include "objectbox.h"
#include "objectbox.hpp"


struct Concept_;

struct Concept {
    obx_id id;
    std::vector<std::string> feature_keys;
    std::vector<std::string> feature_values;

    struct _OBX_MetaInfo {
        static constexpr obx_schema_id entityId() { return 1; }
    
        static void setObjectId(Concept& object, obx_id newId) { object.id = newId; }
    
        /// Write given object to the FlatBufferBuilder
        static void toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Concept& object);
    
        /// Read an object from a valid FlatBuffer
        static Concept fromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static std::unique_ptr<Concept> newFromFlatBuffer(const void* data, size_t size);
    
        /// Read an object from a valid FlatBuffer
        static void fromFlatBuffer(const void* data, size_t size, Concept& outObject);
    };
};

struct Concept_ {
    static const obx::Property<Concept, OBXPropertyType_Long> id;
    static const obx::Property<Concept, OBXPropertyType_StringVector> feature_keys;
    static const obx::Property<Concept, OBXPropertyType_StringVector> feature_values;
};

