// Code generated by ObjectBox; DO NOT EDIT.

#include "concepts.obx.hpp"

const obx::Property<Concept, OBXPropertyType_Long> Concept_::id(1);
const obx::Property<Concept, OBXPropertyType_StringVector> Concept_::feature_keys(2);
const obx::Property<Concept, OBXPropertyType_StringVector> Concept_::feature_values(3);

void Concept::_OBX_MetaInfo::toFlatBuffer(flatbuffers::FlatBufferBuilder& fbb, const Concept& object) {
    fbb.Clear();
    auto offsetfeature_keys = fbb.CreateVectorOfStrings(object.feature_keys);
    auto offsetfeature_values = fbb.CreateVectorOfStrings(object.feature_values);
    flatbuffers::uoffset_t fbStart = fbb.StartTable();
    fbb.AddElement(4, object.id);
    fbb.AddOffset(6, offsetfeature_keys);
    fbb.AddOffset(8, offsetfeature_values);
    flatbuffers::Offset<flatbuffers::Table> offset;
    offset.o = fbb.EndTable(fbStart);
    fbb.Finish(offset);
}

Concept Concept::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t size) {
    Concept object;
    fromFlatBuffer(data, size, object);
    return object;
}

std::unique_ptr<Concept> Concept::_OBX_MetaInfo::newFromFlatBuffer(const void* data, size_t size) {
    auto object = std::make_unique<Concept>();
    fromFlatBuffer(data, size, *object);
    return object;
}

void Concept::_OBX_MetaInfo::fromFlatBuffer(const void* data, size_t, Concept& outObject) {
    const auto* table = flatbuffers::GetRoot<flatbuffers::Table>(data);
    assert(table);
    outObject.id = table->GetField<obx_id>(4, 0);
    {
        auto* ptr = table->GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>*>(6);
        if (ptr) {
            outObject.feature_keys.reserve(ptr->size());
            for (flatbuffers::uoffset_t i = 0; i < ptr->size(); i++) {
                auto* itemPtr = ptr->Get(i);
                if (itemPtr) outObject.feature_keys.emplace_back(itemPtr->c_str());
            }
        } else {
            outObject.feature_keys.clear();
        }
    }
    {
        auto* ptr = table->GetPointer<const flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>*>(8);
        if (ptr) {
            outObject.feature_values.reserve(ptr->size());
            for (flatbuffers::uoffset_t i = 0; i < ptr->size(); i++) {
                auto* itemPtr = ptr->Get(i);
                if (itemPtr) outObject.feature_values.emplace_back(itemPtr->c_str());
            }
        } else {
            outObject.feature_values.clear();
        }
    }
}

